FROM node:14-alpine
RUN mkdir -p /home/server
RUN npm install express
RUN npm install cors
RUN npm install fs
RUN npm install jwt-decode
RUN npm install express-oauth2-jwt-bearer
RUN npm install mongoose
RUN npm install amqplib
COPY . /home/server
EXPOSE 6001
CMD ["node", "/home/server/serverv2.js"]